### ISSUE TITLE
What  tokenizer is used?

### ISSUE THREAD

**Issue by Maykeye** [Zyphra/BlackMamba#6]
I can't see mention of tokenizer.  Original mamba used 
`EleutherAI/gpt-neox-20b`  which has 50277 entries. And this value is mirrored in original [Mamba](https://huggingface.co/state-spaces/mamba-2.8b/blob/b342b33a0c4718008a85682ffbb94a0a51d7ea16/config.json#L4) config.
Here `model.config.vocab_size` has size of [50304](https://huggingface.co/Zyphra/BlackMamba-2.8B/blob/621d8c2e188600a27606205c87339fb28c09ea85/config.json#L1)  and its embedding reflect that as well:

```python
In [56]: model.embedding
Out[56]: Embedding(50304, 1472)

In [57]: len(tokenizer)
Out[57]: 50277
```
It seems to work with EleutherAI/gpt-neox-20b, but maybe it uses some variant of it.

**Comment by Quentin-Anthony** [comment]
Those are padding tokens to get our vocab size to an efficient number. Underlying GPU GEMM kernels are much more efficient at 50304. Learn more in https://arxiv.org/abs/2401.14489
